services:
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: booklist