name: Run test and linter
on: push
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker compose build
      - name: Create and start docker containers
        run: docker compose up -d
      - name: Install libraries for development
        run: docker compose exec app pip install -r ./requirements-dev.txt
      - name: Run test
        run: docker compose exec app pytest
      - name: Stop and remove docker containers
        run: docker compose down